# Manual de numpy

 ¿Por que utilizar numpy en lugar de listas?. Porque numpy es más rápido que utilizar listas. numpy utiliza Fixed Type, por ejemplo int32 y se puede especificar el tamaño que queremos que utilice. Las listas almacenan más información porque guardan Size, Reference Count, Object Type y Object Value. numpy utiliza memoria continua mientas que las listas no. numpy no necesita hacer comprobaciones para cada uno de sus elemento debido a que todos los elemento en un arreglo numpy tienen el mismo tipo. Los arreglos en numpy tienen los mismos métodos que las listas normales y muchos otros más.
Por lo anterior numpy es un remplazo para MATLAB, la instalación de python toma menos de 10 min y configurar un entorno también, mientras que la instalación de MATLAB toma entre 1 y 2 horas. En combinación con Matplotlib es una herramieta muy buena para realizar gráfica. Es el backend para otros paquetes como Pandas y es la base para realizar algoritmos de Machine Learnig.

## 1. Introducción (uso básico)

Lo primero que hay que hacer es importa la libreria de numpy, tradicionalmente se hace de la siguiente manera:

In [30]:
import numpy as np

Para declarar un arreglo sencillo en numpy o un vector 1D lo hacemos de la siguiente manera:

In [31]:
a = np.array([1,3,5])
print(a); print(type(a)); print(a.ndim); print(a.shape); print(a.dtype); print(a.itemsize); print(a.size); print(a.nbytes)
#print(dir(a))

[1 3 5]
<class 'numpy.ndarray'>
1
(3,)
int32
4
3
12


como podemos notar, se utiliza el método `np.array()` el cual toma como argumento una lista de python.

Para crear una matriz 2x2 lo podemos hacer pasando una lista de listas de la siguiente manera:

In [33]:
b = np.array( [ [1.1,2.2,3.3],[4.4,5.5,6.6] ] )
print(b); print(type(b)); print(b.ndim); print(b.shape); print(b.dtype); print(b.itemsize); print(b.size); print(b.nbytes)
#print(dir(b))

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]
<class 'numpy.ndarray'>
2
(2, 3)
float64
8
6
48


## 2. Arreglos

Ya vimos como crear arreglos apartir de listas, sin embardo numpy tiene maneras más eficientes de crear arreglos, acontinuación se muestran algunas de las más importantes:

| Tipo básico | Código |
| --- | --- |
| Matriz | `a = np.array( [ [1,2], [3,4] ] )` |
| Escalar | `b = np.array( [ [1] ] )` |
| Vector renglón | `c = np.array( [ [1,2,3,4]] )` |
| Vector columna | `d = np.array( [ [1],[2],[3],[4] ] )` |


In [34]:
a = np.array( [ [1,2], [3,4] ] ); print(a); print(a.shape); print(a.size); print('')
b = np.array( [ [1] ] ); print(b); print(b.shape); print(b.size);print('')
c = np.array( [ [1,2,3,4]] ); print(c); print(c.shape); print(c.size);print('')
d = np.array( [ [1],[2],[3],[4] ] ); print(d); print(d.shape); print(d.size); print('')

[[1 2]
 [3 4]]
(2, 2)
4

[[1]]
(1, 1)
1

[[1 2 3 4]]
(1, 4)
4

[[1]
 [2]
 [3]
 [4]]
(4, 1)
4



### Funciones para crear arreglos

En la siguiente tabla estan algunas de las funciones con arreglos más importantes:

| Comando | Descripción |
| --- | --- |
| |  |
| | |
| | |
| | |

In [101]:
a = np.arange(11); print(a); print(a.shape); print('')
a = np.arange(1,11); print(a); print(a.shape); print('')
a = np.arange(0,11,2); print(a); print(a.shape); print('')
a = np.linspace(1,5,9); print(a); print(a.shape); print('')
a = np.random.uniform( size=(5) ); print(a); print(a.shape); print('')
a = np.random.uniform( size=(2,2) ); print(a); print(a.shape); print('')
a = np.random.randint(10, size=(5) ); print(a); print(a.shape); print('')
a = np.random.randint(1, high = 10,size=(2,2) ); print(a); print(a.shape); print('')
a = np.ones(5); print(a); print(a.shape); print('')
a = np.ones((2,2)); print(a); print(a.shape); print('')
a = np.zeros(5); print(a); print(a.shape); print('')
a = np.zeros((2,2)); print(a); print(a.shape); print('')
a = np.identity(3); print(a); print(a.shape); print('')
a = np.diag([1,2,3]); print(a); print(a.shape); print('')

[ 0  1  2  3  4  5  6  7  8  9 10]
(11,)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)

[ 0  2  4  6  8 10]
(6,)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
(9,)

[0.63052722 0.21318364 0.81184982 0.65059747 0.11791081]
(5,)

[[0.76942196 0.34165755]
 [0.47504416 0.340768  ]]
(2, 2)

[1 1 6 0 5]
(5,)

[[2 7]
 [7 7]]
(2, 2)

[1. 1. 1. 1. 1.]
(5,)

[[1. 1.]
 [1. 1.]]
(2, 2)

[0. 0. 0. 0. 0.]
(5,)

[[0. 0.]
 [0. 0.]]
(2, 2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
(3, 3)



In [62]:
a = np.arange(1,10).reshape((3,3)); print(a); print(a.shape); print('')
a = np.arange(1,13); a = np.reshape(a, (2,6)); print(a); print(a.shape); print('')
a = np.arange(1,13).reshape((2,6)).transpose(); print(a); print(a.shape); print('')
a = np.arange(1,17).reshape((4,4)); print(a); print(a.shape); print('')
a = a.flatten(); print(a); print(a.shape); print('')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]
(6, 2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)



## 3. Indexación

La indexación es la forma de poder extraer y modificar los valores de los arreglos. La posición de un valor dentro de un arreglo es su índice. El índice se puede utilizar para extraer valores concretos.

Supongamos un vector de la forma `x = np.arange(1,11) `, entonces podemos realizar las siguientes indexaciones:

| Comando | Descripción |
| --- | --- |
| |  |
| | |
| | |
| | |


In [128]:
x = np.arange(1,11); print(x); print(x.shape); print(x.size); print('')
print(x[0]); print('')         # Primer elemento
print(x[-1]); print('')        # Ultimo elemento
print(x[1:5]); print('')       # Desde el indice 1 hasta el indice 4
print(x[:5]); print('')        # Desde el primer al cuarto indice
print(x[3:]); print('')        # Desde el indice 3 al ultimo
print(x[:-1]); print('')       # Dede el primer al penultimo indice
print(x[::2]); print('')       # Desde el primer al ultimo indice en pasos de 2
print(x[::-1]); print('')      # Voltear el arreglo
print(x[::-1][::2]); print('') # Voltear el arreglo con un paso de 2
print(x[:]); print('')         # Todo el arreglo

[ 1  2  3  4  5  6  7  8  9 10]
(10,)
10

1

10

[2 3 4 5]

[1 2 3 4 5]

[ 4  5  6  7  8  9 10]

[1 2 3 4 5 6 7 8 9]

[1 3 5 7 9]

[10  9  8  7  6  5  4  3  2  1]

[10  8  6  4  2]

[ 1  2  3  4  5  6  7  8  9 10]



Supongamos un vector de la forma `x = np.arange(1,10).reshape((3,3))` , entonces podemos realizar las siguientes indexaciones:

In [166]:
x = np.arange(1,10).reshape((3,3)); print(x); print(x.shape); print(x.size); print('')
print(x[1,1]); print('')     # Indice 1,1  5
print(x[0,0]); print('')     # Indice 0,0  1

print(x[1,:]); print('')     # Renglon 2
print(x[1:3,:]); print('')   # Renglon 2 y 3
print(x[-1,:]); print('')    # Ultimo renglon

print(x[:,0]); print('')     # Primera columna
print(x[:,-1]); print('')    # Ultima columna
print(x[:,:2]); print('')    # Todos los renglones, columna 0 a 1
print(x[:,[0,2]]); print('') # Todos los renglones, columna 0 y 2
print(x[1:,1:]); print('')   # Submatriz


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9

5

1

[4 5 6]

[[4 5 6]
 [7 8 9]]

[7 8 9]

[1 4 7]

[3 6 9]

[[1 2]
 [4 5]
 [7 8]]

[[1 3]
 [4 6]
 [7 9]]

[[5 6]
 [8 9]]

[[ 1  2 99]
 [ 4  5 99]
 [ 7  8 99]]
